#- name: include OS-specific variables
#  include_vars: "{{ ansible_distribution }}.yml"
  
- include: "{{ ansible_os_family }}.yml"
  become: yes

- name: make directory
  file:
    path: "{{letsencrypt_directory}}"
    state: directory
    mode: 0777
  become: yes

- name: download certbot-auto
  get_url: 
    url: https://dl.eff.org/certbot-auto
    dest: "{{letsencrypt_directory}}"
    mode: 0755
  become: yes
  become_user: "{{letsencrypt_user}}"

- name: generate cert
  shell: "{{letsencrypt_directory}}/./certbot-auto -n certonly --server https://acme-v01.api.letsencrypt.org/directory -a webroot --webroot-path={{letsencrypt_directory}} --agree-tos --email {{letsencrypt_email}} {{letsencrypt_domainstring}}"
  become: yes
  become_user: "{{letsencrypt_user}}"

- name: setup cronjob
  cron:
    name: letsencrypt renew
    minute: '0'
    hour: '{{renew_hour}}'
    day: '*'
    state: present
    job: ./certbot-auto -n renew && sudo nginx -s reload
  become: yes
  become_user: "{{letsencrypt_user}}"